---
title: "3. Post-EM Statistical Evaluation and Visualization"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

1. Environment Setup & Data Import

```{r}
library(Signac)
library(Seurat)
library(ggplot2)
library(dplyr)
library(uwot)
library(tidyr)
library(tibble)

# Load context variables saved during preprocessing
load("scATAC_preB_all_bi.RData")

# Read state vectors generated by your EM Notebook
cell_group <- unlist(as.vector(read.csv("cell_states_bi_preB.csv")))
cell_group <- abs(1 - cell_group) # Re-orient mappings if indices are inverted
```

2. Statistical Evaluation of State-Specific Coverage

```{r}
coverage_list <- list()
ks_pvalues <- c()
t_test_pvalues <- c()
states <- 0:1

for (state in states) {
  coverage <- data.frame(row.names = row.names(c1_sums[, cell_group == state]))
  coverage$state <- state
  coverage$annt <- early
  
  coverage["genome1"] <- rowSums(c1_sums[, cell_group == state])
  coverage["genome2"] <- rowSums(c2_sums[, cell_group == state])
  
  coverage["genome1_norm"] <- coverage["genome1"] / sum(coverage["genome1"])
  coverage["genome2_norm"] <- coverage["genome2"] / sum(coverage["genome2"])
  coverage["total_cov"] <- coverage["genome1"] + coverage["genome2"]
  
  coverage <- coverage[abs(coverage$total_cov - mean(coverage$total_cov, na.rm = TRUE)) < 3 * sd(coverage$total_cov), ]
  coverage <- coverage[is.finite(coverage$genome1_norm) & is.finite(coverage$genome2_norm), ]
  coverage <- coverage[coverage$total_cov > 0, ]
  
  coverage["log2_ratio"] <- log2(coverage["genome1_norm"] / coverage["genome2_norm"])
  
  ks_test <- ks.test(coverage$log2_ratio ~ coverage$annt)
  ks_pvalues <- c(ks_pvalues, ks_test$p.value)
  
  if(state < 2) {
     t_test <- t.test(log2_ratio ~ annt, data = coverage)
     t_test_pvalues <- c(t_test_pvalues, t_test$p.value)
  }
  coverage_list[[state + 1]] <- coverage
}

coverage_combined <- do.call(rbind, coverage_list)
state_percentages <- table(cell_group) / sum(table(cell_group)) * 100

coverage_combined$state_label <- paste0(
  "State ", coverage_combined$state + 1, 
  " (", round(state_percentages[as.character(coverage_combined$state)], 1), "%, ",
  "KS p = ", formatC(ks_pvalues[coverage_combined$state + 1], format = "e", digits = 2), ", ",
  "T p = ", formatC(t_test_pvalues[coverage_combined$state + 1], format = "e", digits = 2), ")"
)

ggplot(coverage_combined, aes(x = log2_ratio, fill = reorder(annt, -as.numeric(annt)))) +
  geom_density(alpha = 0.8) +
  facet_wrap(~state_label, ncol = 1, scales = "free") +
  xlim(c(-5, 5)) +
  xlab("C57BL/CAST - ATAC (log2)") +
  ylab("Frequency") +
  scale_fill_brewer(palette = "Set2") +
  theme_classic() +
  labs(fill = NULL)
```

3. Generate Genome Browser Tracks (Bedgraph)

```{r}
coverage_geo <- coverage_combined %>%
  rownames_to_column(var = "row_names") %>%
  separate(row_names, into = c("chr", "start", "end"), sep = "-", convert = TRUE) %>%
  filter(is.finite(log2_ratio)) %>%
  select(chr, start, end, log2_ratio)

write.table(coverage_geo, "coverage_keep_bi.bedgraph", sep="\t", row.names = FALSE, col.names = FALSE, quote = FALSE)
```

4. Semi-Supervised Dimensional Reduction Manifold

```{r}
ratio_matrix <- log2(c1_sums[["peaks"]]@counts + 0.1) / (c2_sums[["peaks"]]@counts + 0.1)
ratio_matrix_filter <- ratio_matrix[, cell_group != 2]
cell_group_filter <- cell_group[cell_group != 2]

chrom_assay_f <- CreateChromatinAssay(ratio_matrix_filter, sep = c(":", "-"), genome = 'GRCm38', fragments = "scATAC_preB_all/fragments.tsv.gz")
data_filter <- CreateSeuratObject(counts = chrom_assay_f, assay = "peaks")

data_filter <- RunTFIDF(data_filter) %>%
               FindTopFeatures(min.cutoff = 'q0') %>%
               RunSVD() %>%
               ScaleData(features = rownames(data_filter)) %>%
               RunPCA()

names(cell_group_filter) <- colnames(data_filter)
data_filter$cell_group <- 1 - cell_group_filter

# Guided supervised UMAP implementation using uwot
umap_embedding <- umap(
    X = data_filter@reductions$pca@cell.embeddings,
    y = cell_group_filter,
    n_neighbors = 2,
    min_dist = 0.0001,
    n_components = 30,
    target_weight = 1
)

data_filter@reductions$umap1 <- CreateDimReducObject(
    embeddings = -umap_embedding,
    key = "UMAP_",
    assay = DefaultAssay(data_filter)
)

DimPlot(data_filter, reduction = "umap1", group.by = "cell_group") + 
  theme_classic() + 
  ggtitle("Semi-Supervised Manifold (EM State Guided)")
```


